name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Frontend image to DockerHub
      - name: Build and push Frontend image
        run: |
          docker build -t savindugunasekara/orphanagefront:latest -f ./frontend/Dockerfile ./frontend
          docker push savindugunasekara/orphanagefront:latest

      # Step 5: Build and push Backend image to DockerHub
      - name: Build and push Backend image
        run: |
          docker build -t savindugunasekara/orphanageback:latest -f ./backend/Dockerfile ./backend
          docker push savindugunasekara/orphanageback:latest
