name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Frontend image to DockerHub
      - name: Build and push Frontend image
        run: |
          docker buildx build --platform linux/amd64 -t savindugunasekara/orphanagefront:latest -f ./adminfrontend/Dockerfile ./adminfrontend --push

      # Step 5: Build and push Backend image to DockerHub
      - name: Build and push Backend image
        run: |
          docker buildx build --platform linux/amd64 -t savindugunasekara/orphanageback:latest -f ./backend/Dockerfile ./backend --push

  deploy:
    # Ensures that the deploy job runs only after the build job is successful
    needs: build
    runs-on: self-hosted

    steps:
      # Step 1: Pull and run Frontend container from DockerHub
      - name: Deploy Frontend container
        run: |
          docker pull savindugunasekara/orphanagefront:latest
          docker stop orphanagefront || true && docker rm orphanagefront || true
          docker run --rm -d --name orphanagefront -p 3000:3000 savindugunasekara/orphanagefront:latest

      # Step 2: Pull and run Backend container from DockerHub
      - name: Deploy Backend container
        run: |
          echo "${{ secrets.ENV }}" > .env
          docker pull savindugunasekara/orphanageback:latest
          docker stop orphanageback || true && docker rm orphanageback || true
          docker run -d \
            --env-file .env \
            -p 4000:4000 \
            --rm --name orphanageback savindugunasekara/orphanageback:latest
